# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7eebcf1f2b77d7b2999fd6c5788c47d311c328cd98938031e233acb6ea29969262f6e87c136abf9d22bb1c7636e265ae7ef6f16d03019c269f209e847f72039

test:
  secret_key_base: 1a54bb0c3594f381408d0f0e43095fb968e0de1100c1e8ac5cf56cd444621d8f7bd6cd5bbb2c8259c30c6a485b15db03bc9c82ce59dc0bbbb418d2f014775a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
